from obtenerObjetosBD.obtenerBorrado import generarProcedimientoAlmacenadoBorrado
from obtenerObjetosBD.obtenerActualizacion import generarProcedimientoAlmacenadoActualizacion
from obtenerObjetosBD.obtenerConsulta import generarProcedimientoAlmacenadoSelect
from obtenerObjetosBD.obtenerInsercion import generarProcedimientoAlmacenadoInsercion