from obtenerObjetosBD.obtenerBorrado import crearSPEliminacionDatos
from obtenerObjetosBD.obtenerActualizacion import crearSPActualizacionDatos
from obtenerObjetosBD.obtenerConsulta import generarProcedimientoAlmacenadoSelect
from obtenerObjetosBD.obtenerInsercion import generarProcedimientoAlmacenadoInsercion